version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "https://github.com/smarlowucf/wxcast"
    commit-message:
      prefix: "pip"

  - package-ecosystem: "bundler"
    vendor: true
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "jekyll"
      - dependency-name: "jekyll-mentions"
      - dependency-name: "jekyll-deploy"
    commit-message:
      prefix: "bundler"
